//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBL.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BasicShapes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicShapes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBL.Repository.Resources.BasicShapes", typeof(BasicShapes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string BannerShape {
            get {
                return ResourceManager.GetString("BannerShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damsel.
        /// </summary>
        internal static string DamselShape {
            get {
                return ResourceManager.GetString("DamselShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishShape {
            get {
                return ResourceManager.GetString("EnglishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GermanShape {
            get {
                return ResourceManager.GetString("GermanShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string ItalianShape {
            get {
                return ResourceManager.GetString("ItalianShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladies.
        /// </summary>
        internal static string LadiesShape {
            get {
                return ResourceManager.GetString("LadiesShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern French.
        /// </summary>
        internal static string ModernFrenchShape {
            get {
                return ResourceManager.GetString("ModernFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old French.
        /// </summary>
        internal static string OldFrenchShape {
            get {
                return ResourceManager.GetString("OldFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string PolishShape {
            get {
                return ResourceManager.GetString("PolishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish / Portuguese / Flemish.
        /// </summary>
        internal static string SpanishShape {
            get {
                return ResourceManager.GetString("SpanishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        internal static string SwissShape {
            get {
                return ResourceManager.GetString("SwissShape", resourceCulture);
            }
        }
    }
}
