//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBlason.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlasonVocabulary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlasonVocabulary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBlason.Culture.BlasonVocabulary", typeof(BlasonVocabulary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string BannerShape {
            get {
                return ResourceManager.GetString("BannerShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string ChargeViewModel {
            get {
                return ResourceManager.GetString("ChargeViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat of Arms.
        /// </summary>
        public static string CoatOfArmViewModel {
            get {
                return ResourceManager.GetString("CoatOfArmViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damsel.
        /// </summary>
        public static string DamselShape {
            get {
                return ResourceManager.GetString("DamselShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division ({0}).
        /// </summary>
        public static string DivisionViewModel {
            get {
                return ResourceManager.GetString("DivisionViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishShape {
            get {
                return ResourceManager.GetString("EnglishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string FieldViewModel {
            get {
                return ResourceManager.GetString("FieldViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ermine.
        /// </summary>
        public static string FurErmine {
            get {
                return ResourceManager.GetString("FurErmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ermines.
        /// </summary>
        public static string FurErmines {
            get {
                return ResourceManager.GetString("FurErmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erminois.
        /// </summary>
        public static string FurErminois {
            get {
                return ResourceManager.GetString("FurErminois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pean.
        /// </summary>
        public static string FurPean {
            get {
                return ResourceManager.GetString("FurPean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vair.
        /// </summary>
        public static string FurVair {
            get {
                return ResourceManager.GetString("FurVair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string GermanShape {
            get {
                return ResourceManager.GetString("GermanShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string ItalianShape {
            get {
                return ResourceManager.GetString("ItalianShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady.
        /// </summary>
        public static string LadiesShape {
            get {
                return ResourceManager.GetString("LadiesShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LineViewModel {
            get {
                return ResourceManager.GetString("LineViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern French (Empire).
        /// </summary>
        public static string ModernFrenchShape {
            get {
                return ResourceManager.GetString("ModernFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoShape {
            get {
                return ResourceManager.GetString("NoShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old French.
        /// </summary>
        public static string OldFrenchShape {
            get {
                return ResourceManager.GetString("OldFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition.
        /// </summary>
        public static string PartitionViewModel {
            get {
                return ResourceManager.GetString("PartitionViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string PartViewModel {
            get {
                return ResourceManager.GetString("PartViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Bend.
        /// </summary>
        public static string PartyBend {
            get {
                return ResourceManager.GetString("PartyBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Bend Sinister.
        /// </summary>
        public static string PartyBendSinister {
            get {
                return ResourceManager.GetString("PartyBendSinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Cross.
        /// </summary>
        public static string PartyCross {
            get {
                return ResourceManager.GetString("PartyCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Fess.
        /// </summary>
        public static string PartyFess {
            get {
                return ResourceManager.GetString("PartyFess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Pale.
        /// </summary>
        public static string PartyPale {
            get {
                return ResourceManager.GetString("PartyPale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Pall.
        /// </summary>
        public static string PartyPall {
            get {
                return ResourceManager.GetString("PartyPall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string PartyPlain {
            get {
                return ResourceManager.GetString("PartyPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party per Saltire.
        /// </summary>
        public static string PartySaltire {
            get {
                return ResourceManager.GetString("PartySaltire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary.
        /// </summary>
        public static string PieceViewModel {
            get {
                return ResourceManager.GetString("PieceViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string PolishShape {
            get {
                return ResourceManager.GetString("PolishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionViewModel {
            get {
                return ResourceManager.GetString("PositionViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enamel.
        /// </summary>
        public static string PropertyNameEnamel {
            get {
                return ResourceManager.GetString("PropertyNameEnamel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string PropertyNameShape {
            get {
                return ResourceManager.GetString("PropertyNameShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish / Portuguese / Flamish.
        /// </summary>
        public static string SpanishShape {
            get {
                return ResourceManager.GetString("SpanishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        public static string SwissShape {
            get {
                return ResourceManager.GetString("SwissShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tierced per Bend.
        /// </summary>
        public static string TiercedBend {
            get {
                return ResourceManager.GetString("TiercedBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tierced per Bend Sinister.
        /// </summary>
        public static string TiercedBendSinister {
            get {
                return ResourceManager.GetString("TiercedBendSinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tierced per Fess.
        /// </summary>
        public static string TiercedFess {
            get {
                return ResourceManager.GetString("TiercedFess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tierced per Pale.
        /// </summary>
        public static string TiercedPale {
            get {
                return ResourceManager.GetString("TiercedPale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cendrée.
        /// </summary>
        public static string TinctureAcier {
            get {
                return ResourceManager.GetString("TinctureAcier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argent.
        /// </summary>
        public static string TinctureArgent {
            get {
                return ResourceManager.GetString("TinctureArgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        public static string TinctureAzure {
            get {
                return ResourceManager.GetString("TinctureAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnation.
        /// </summary>
        public static string TinctureCarnation {
            get {
                return ResourceManager.GetString("TinctureCarnation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gules.
        /// </summary>
        public static string TinctureGules {
            get {
                return ResourceManager.GetString("TinctureGules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murrey.
        /// </summary>
        public static string TinctureMurrey {
            get {
                return ResourceManager.GetString("TinctureMurrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string TinctureOr {
            get {
                return ResourceManager.GetString("TinctureOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenné.
        /// </summary>
        public static string TinctureOrange {
            get {
                return ResourceManager.GetString("TinctureOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper.
        /// </summary>
        public static string TinctureProper {
            get {
                return ResourceManager.GetString("TinctureProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpure.
        /// </summary>
        public static string TincturePurpure {
            get {
                return ResourceManager.GetString("TincturePurpure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sable.
        /// </summary>
        public static string TinctureSable {
            get {
                return ResourceManager.GetString("TinctureSable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanguine.
        /// </summary>
        public static string TinctureSanguine {
            get {
                return ResourceManager.GetString("TinctureSanguine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert.
        /// </summary>
        public static string TinctureVert {
            get {
                return ResourceManager.GetString("TinctureVert", resourceCulture);
            }
        }
    }
}
