//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBlason.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BlasonVocabulary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlasonVocabulary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBlason.Culture.BlasonVocabulary", typeof(BlasonVocabulary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string BannerShape {
            get {
                return ResourceManager.GetString("BannerShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string ChargeViewModel {
            get {
                return ResourceManager.GetString("ChargeViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat of Arms.
        /// </summary>
        internal static string CoatOfArmViewModel {
            get {
                return ResourceManager.GetString("CoatOfArmViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damsel.
        /// </summary>
        internal static string DamselShape {
            get {
                return ResourceManager.GetString("DamselShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishShape {
            get {
                return ResourceManager.GetString("EnglishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string FieldViewModel {
            get {
                return ResourceManager.GetString("FieldViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GermanShape {
            get {
                return ResourceManager.GetString("GermanShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string ItalianShape {
            get {
                return ResourceManager.GetString("ItalianShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady.
        /// </summary>
        internal static string LadiesShape {
            get {
                return ResourceManager.GetString("LadiesShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string LineViewModel {
            get {
                return ResourceManager.GetString("LineViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern French (Empire).
        /// </summary>
        internal static string ModernFrenchShape {
            get {
                return ResourceManager.GetString("ModernFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoShape {
            get {
                return ResourceManager.GetString("NoShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old French.
        /// </summary>
        internal static string OldFrenchShape {
            get {
                return ResourceManager.GetString("OldFrenchShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition.
        /// </summary>
        internal static string PartitionViewModel {
            get {
                return ResourceManager.GetString("PartitionViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string PartViewModel {
            get {
                return ResourceManager.GetString("PartViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary.
        /// </summary>
        internal static string PieceViewModel {
            get {
                return ResourceManager.GetString("PieceViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string PolishShape {
            get {
                return ResourceManager.GetString("PolishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string PositionViewModel {
            get {
                return ResourceManager.GetString("PositionViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enamel.
        /// </summary>
        internal static string PropertyNameEnamel {
            get {
                return ResourceManager.GetString("PropertyNameEnamel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string PropertyNameShape {
            get {
                return ResourceManager.GetString("PropertyNameShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish / Portuguese / Flamish.
        /// </summary>
        internal static string SpanishShape {
            get {
                return ResourceManager.GetString("SpanishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract layer.
        /// </summary>
        internal static string SubjectiveLayerViewModel {
            get {
                return ResourceManager.GetString("SubjectiveLayerViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        internal static string SwissShape {
            get {
                return ResourceManager.GetString("SwissShape", resourceCulture);
            }
        }
    }
}
